# For details on connection pooling, see Rails configuration guide
# http://guides.rubyonrails.org/configuring.html#database-pooling

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['SAQR_API_DATABASE_USERNAME'] %>
  password: <%= ENV['SAQR_API_DATABASE_PASSWORD'] %>
  host: <%= ENV['SAQR_API_DATABASE_HOST'] %>
  port: <%= ENV['SAQR_API_DATABASE_PORT'] %>

development:
  <<: *default
  database: SAQR_API_development

test:
  <<: *default
  database: SAQR_API_test

production:
  <<: *default
  database: SAQR_API_production
  username: SAQR_API
  password: <%= ENV['SAQR_API_DATABASE_PASSWORD'] %>
